---
- hosts: controller_nodes
  become: true
  gather_facts: no
  tasks:
    - name: restart nova-services
      service: name={{ item }} state=restarted enabled=yes
      loop:
        - nova-api
        - nova-scheduler
        - nova-conductor
        - nova-spiceproxy

- hosts: compute_nodes
  become: true
  gather_facts: no
  tasks:
    - name: restart nova-compute
      service: name=nova-compute state=restarted
