- name: Ensure apt info is updated
  apt: update_cache=yes


- name: Add OpenStack repository
  command: add-apt-repository -y cloud-archive:caracal
 
- name: Ensure system is updated and upgraded
  apt: update_cache=yes upgrade=yes

  
- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].internal_ip }} {{item}}" state=present
  when: hostvars[item].internal_ip is defined
  with_items: "{{ groups.all }}"






