
- name: restart trove-services
  service: name={{ item }} state=restarted
  with_items:
    - trove-api
    - trove-taskmanager
    - trove-conductor

- name: restart web services
  service: name={{ item }} state=restarted
  with_items:
    - apache2
    - memcached