- name: ensure cinder packages are installed
  apt: name={{ item }}
  loop:
    - cinder-api 
    - cinder-scheduler

- name: ensure cinder_api database connections is configured
  ini_file:
    path: /etc/cinder/cinder.conf
    section: database
    option: connection
    value: mysql+pymysql://cinder:{{ cinder_db_password }}@{{ internal_ip }}/cinder
  notify: 
  - restart cinder-services

- name: set default section options
  ini_file:
    path: /etc/cinder/cinder.conf
    section: DEFAULT
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "transport_url", value: 'rabbit://{{ rabbit_user }}:{{ rabbit_password }}@{{ internal_ip }}:5672/'}
    - { option: "my_ip", value: '{{ internal_ip }}' }
    - { option: "auth_strategy", value: keystone }
    #- { option: "glance_api_servers", value: 'http://{{ hostvars[groups["storage_nodes"][0]]["internal_ip"] }}:9292' }
  notify: 
  - restart cinder-services

- name: configure keystone_authtoken section
  ini_file:
    path: /etc/cinder/cinder.conf
    section: keystone_authtoken
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "www_authenticate_uri", value: 'http://{{ internal_ip }}:5000' }
    - { option: "auth_url", value: 'http://{{ internal_ip }}:5000' }
    - { option: "memcached_servers", value: '{{ internal_ip }}:11211' }
    - { option: "auth_type", value: password }
    - { option: "project_domain_name", value: Default}
    - { option: "user_domain_name", value: Default}
    - { option: "project_name", value: service}
    - { option: "username", value: cinder}
    - { option: "password", value: "{{ cinder_identity_password }}" }
    #- { option: "region", value: "{{ region }}" }    
    #- { option: "region_name", value: "{{ region }}" }    
    - { option: "service_token_roles_required", value: true } # Solución problema cinder-nova https://docs.openstack.org/cinder/latest/configuration/block-storage/service-token.html
    - { option: "service_token_roles", value: service } # Solución problema cinder-nova https://docs.openstack.org/cinder/latest/configuration/block-storage/service-token.html
  notify: 
  - restart cinder-services

## Solución problema cinder-nova 
## https://docs.openstack.org/cinder/latest/configuration/block-storage/service-token.html
- name: configure service_user section
  ini_file:
    path: /etc/cinder/cinder.conf
    section: service_user
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "www_authenticate_uri", value: 'http://{{ internal_ip }}:5000' }
    - { option: "auth_url", value: 'http://{{ internal_ip }}:5000' }
    - { option: "memcached_servers", value: '{{ internal_ip }}:11211' }
    - { option: "send_service_user_token", value: True }
    - { option: "auth_type", value: password }
    - { option: "project_domain_name", value: Default}
    - { option: "user_domain_name", value: Default}
    - { option: "project_name", value: service}
    - { option: "username", value: nova}
    - { option: "password", value: "{{ nova_identity_password }}" }
  notify: 
  - restart cinder-services


- name: configure oslo_concurrency section
  ini_file:
    path: /etc/cinder/cinder.conf
    section: oslo_concurrency
    option: lock_path
    value: /var/lib/cinder/tmp
  notify:
  - restart cinder-services

- name: ensure cinder db is initialized
  command: /usr/bin/cinder-manage db sync
  notify: restart cinder-services
