- name: ensure glance is installed
  apt: name=glance

- name: ensure glance database connection is configured
  ini_file:
    path: /etc/glance/glance-api.conf
    section: database
    option: connection
    value: mysql+pymysql://glance:{{ glance_db_password }}@{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}/glance
  notify:
  - restart glance-api

- name: ensure glance_authtoken is configured
  ini_file:
    path: /etc/glance/glance-api.conf
    section: keystone_authtoken
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "www_authenticate_uri", value: 'http://{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:5000' }
    - { option: "auth_url", value: 'http://{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:5000' }
    - { option: "memcached_servers", value: '{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:11211' }
    - { option: "auth_type", value: password }
    - { option: "project_domain_name", value: Default}
    - { option: "user_domain_name", value: Default}
    - { option: "project_name", value: service}
    - { option: "username", value: glance}
    - { option: "password", value: "{{ glance_identity_password }}" }
  notify:
  - restart glance-api


- name: ensure paste_deploy is set to glance
  ini_file:
    path: /etc/glance/glance-api.conf
    section: paste_deploy
    option: flavor
    value: keystone
  notify:
  - restart glance-api

- name: ensure DEFAULT is set to glance
  ini_file:
    path: /etc/glance/glance-api.conf
    section: DEFAULT
    option: "enabled_backends"
    value: "fs:file"
  notify:
  - restart glance-api

- name: ensure glance_store is set to glance
  ini_file:
    path: /etc/glance/glance-api.conf
    section: glance_store
    option: default_backend
    value: fs
  notify:
  - restart glance-api

- name: ensure fs is set to glance
  ini_file:
    path: /etc/glance/glance-api.conf
    section: fs
    option: filesystem_store_datadir
    value: /var/lib/glance/images/
  notify:
  - restart glance-api


- name: ensure oslo_limit is set to glance
  ini_file:
    path: /etc/glance/glance-api.conf
    section: oslo_limit
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "auth_url", value: 'http://{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:5000' }
    - { option: "auth_type", value: 'password' }
    - { option: "user_domain_id", value: 'default' }
    - { option: "username", value: 'glance' }
    - { option: "system_scope", value: 'all' }
    - { option: "password", value: '{{ glance_identity_password }}' }
    - { option: "endpoint_id", value: 'RegionOne-image-public' }
    - { option: "region_name", value: '{{region}}' }
    
  notify:
  - restart glance-api




- name: ensure glance db is initialized
  command: /usr/bin/glance-manage db_sync
  notify:
  - restart glance-api
  
